### ISSUE TITLE
Bot is struggling to parse tu command

### ISSUE THREAD

**Issue by ashchow95** [ANTFOR7717/AutoWaifuClaimerV3#3]
Hey,

Been trying to diagnose the issue since you have updated to the docker. I have ensured that all the entry in the config file is accurate (Mudae Bot's ID, Server ID, Chanenl ID, and my user ID). I have ensured that my bot token is correct in the config file and that the bot has read message privilege and view channel privilege. Our server uses a . instead of $ for rolls and it is accurately represented. Our server also allows for us to input command with a slash as well to get mudae to roll for you. As well, my personal tu arrange is set to default.

No matter what method I have tried, I have not been able to get the bot to properly parse my timers. Any suggested avenue for diagnosing next?

**Comment by ANTFOR7717** [comment]
Hey @ashchow95, 

I have actually recognized this same issue, I'm not entirely sure where it's coming from; It happened to me one night, I had no idea why, I tried everything and every parsing command, and even changed the bot token. I finally just restarted my entire computer and it started working again. If you haven't tried the above steps I would try that. I have forked from this repository with no extra code added and it has since been parsing properly. I'll try to build tools to debug this issue since I'm not sure if its a code related issue or discord related issue.

**Comment by ashchow95** [comment]
Just to verify, when we test $tu (or whatever the server config is for commands. It is

1) Not the /tu command that makes Mudae bot quene it up
2) It can be either a browser discord or a discord desktop client that initiates the $tu

**Comment by ANTFOR7717** [comment]
@ashchow95 Yes, as long as the command is outputted the bot in the server will see it and send it to the python program to have it parsed. I should also mention that you need to have the **vanilla** $tu command because custom ones can't be parsed, so that could be your issue.

**Comment by ANTFOR7717** [comment]
@ashchow95 I've rebuilt my container and am having the same issue. More solutions to follow soon.

**Comment by ANTFOR7717** [comment]
@ashchow95 you'll definitely find the `logging.info()` method very useful if you do any debugging
